const express = require('express');
const Order = require('../models/Order');
const Product = require('../models/Product');
const { protect } = require('../middleware/auth');
const mongoose = require('mongoose');

const router = express.Router();

// POST /api/orders - create order
router.post('/', protect, async (req, res) => {
  try {
    const { orderItems, shippingAddress, paymentMethod } = req.body;
    
    if (!orderItems || orderItems.length === 0) {
      return res.status(400).json({ message: 'No order items' });
    }

    // Calculate prices and verify stock
    let itemsPrice = 0;
    const items = [];
    
    // Process each order item
    for (const item of orderItems) {
      const product = await Product.findById(item.product);
      if (!product) {
        return res.status(400).json({ message: `Product not found: ${item.product}` });
      }
      if (product.countInStock < item.qty) {
        return res.status(400).json({ 
          message: `Insufficient stock for product: ${product.name}` 
        });
      }
      
      // Update product stock
      product.countInStock -= item.qty;
      await product.save();
      
      // Add to items array with all required fields
      items.push({
        product: product._id,
        name: product.name,
        qty: item.qty,
        price: product.price,
        image: product.image || 'https://via.placeholder.com/400x300?text=Product'
      });
      
      itemsPrice += product.price * item.qty;
    }

    // Calculate prices
    const taxPrice = Number((0.1 * itemsPrice).toFixed(2));
    const shippingPrice = itemsPrice > 1000 ? 0 : 100;
    const totalPrice = Number((itemsPrice + taxPrice + shippingPrice).toFixed(2));

    // Create the order
    const order = new Order({
      user: req.user.id,
      orderItems: items,
      shippingAddress,
      paymentMethod,
      itemsPrice,
      taxPrice,
      shippingPrice,
      totalPrice,
      isPaid: false,
      isDelivered: false
    });

    const createdOrder = await order.save();

    // Return the created order with 201 status
    res.status(201).json({
      _id: createdOrder._id,
      orderId: createdOrder.orderId, // This will be auto-generated by the schema
      user: createdOrder.user,
      orderItems: createdOrder.orderItems,
      shippingAddress: createdOrder.shippingAddress,
      paymentMethod: createdOrder.paymentMethod,
      itemsPrice: createdOrder.itemsPrice,
      taxPrice: createdOrder.taxPrice,
      shippingPrice: createdOrder.shippingPrice,
      totalPrice: createdOrder.totalPrice,
      isPaid: createdOrder.isPaid,
      isDelivered: createdOrder.isDelivered,
      createdAt: createdOrder.createdAt
    });

  } catch (error) {
    console.error('Error creating order:', error);
    res.status(500).json({ 
      message: 'Error creating order',
      error: process.env.NODE_ENV === 'development' ? error.message : undefined
    });
  }
});

// GET /api/orders/my - get logged in user orders
router.get('/my', protect, async (req, res) => {
  try {
    const orders = await Order.find({ user: req.user.id });
    res.json(orders);
  } catch (error) {
    console.error('Error fetching user orders:', error);
    res.status(500).json({ message: 'Error fetching orders' });
  }
});

// PUT /api/orders/:id/return - return an order
router.put('/:id/return', protect, async (req, res) => {
  try {
    const order = await Order.findById(req.params.id);
    
    if (!order) {
      return res.status(404).json({ message: 'Order not found' });
    }

    // Check if order belongs to user
    if (order.user.toString() !== req.user.id) {
      return res.status(401).json({ message: 'Not authorized to return this order' });
    }

    // Check if order is already returned
    if (order.isReturned) {
      return res.status(400).json({ message: 'Order has already been returned' });
    }

    // Check if order is delivered
    if (!order.isDelivered) {
      return res.status(400).json({ message: 'Only delivered orders can be returned' });
    }

    // Start a session for transaction
    const session = await mongoose.startSession();
    session.startTransaction();

    try {
      // Restore product quantities
      for (const item of order.orderItems) {
        await Product.findByIdAndUpdate(
          item.product,
          { $inc: { countInStock: item.qty } },
          { session }
        );
      }

      // Mark order as returned
      order.isReturned = true;
      order.returnedAt = Date.now();
      await order.save({ session });

      // Fetch the updated order with all fields
      const updatedOrder = await Order.findById(order._id);
      
      await session.commitTransaction();
      session.endSession();

      res.json({ 
        message: 'Order returned successfully',
        order: updatedOrder
      });
    } catch (error) {
      await session.abortTransaction();
      session.endSession();
      throw error;
    }
  } catch (error) {
    console.error('Error fetching orders:', error);
    res.status(500).json({ message: 'Error fetching orders' });
  }
});

// GET /api/orders/:id - get order by ID
router.get('/:id', protect, async (req, res) => {
  try {
    const order = await Order.findById(req.params.id).populate('user', 'name email');
    
    if (!order) {
      return res.status(404).json({ message: 'Order not found' });
    }
    
    // Make sure the order belongs to the user or the user is an admin
    if (order.user._id.toString() !== req.user.id.toString() && !req.user.isAdmin) {
      return res.status(401).json({ message: 'Not authorized' });
    }
    
    res.json(order);
  } catch (error) {
    console.error('Error fetching order:', error);
    res.status(500).json({ message: 'Error fetching order' });
  }
});

module.exports = router;